import path from 'node:path';
import { Readable } from 'node:stream';
import { fileTypeFromBuffer } from 'file-type';

/** file-type needs about this much to recognise every format it knows. */
export const SNIFF_BYTES = 4100;

const FALLBACK = 'application/octet-stream';

/**
 * Only formats that are inert when served as an attachment. HTML and SVG are
 * deliberately absent: they fall through to octet-stream.
 */
const TEXT_EXTENSIONS: Record<string, string> = {
  '.txt': 'text/plain',
  '.log': 'text/plain',
  '.csv': 'text/csv',
  '.md': 'text/markdown',
  '.json': 'application/json',
  '.xml': 'application/xml',
};

/**
 * The client's filename is a display name and nothing else: no path
 * separators, no control characters, no leading/trailing space, 255 max.
 * Storage keys are generated by us and never derived from this.
 */
export function sanitiseFilename(raw: string): string {
  const base = raw.split(/[\\/]/).pop() ?? '';
  // eslint-disable-next-line no-control-regex
  const cleaned = base.replace(/[\u0000-\u001f\u007f]/g, '').trim();

  if (cleaned.length === 0 || cleaned === '.' || cleaned === '..') return 'unnamed';
  return cleaned.slice(0, 255);
}

function looksLikeText(head: Buffer): boolean {
  if (head.includes(0)) return false;

  // A multi-byte character can straddle the sniff boundary, so allow up to
  // three trailing bytes to be dropped before calling it binary.
  for (let trim = 0; trim <= 3 && trim < head.length; trim += 1) {
    try {
      new TextDecoder('utf-8', { fatal: true }).decode(head.subarray(0, head.length - trim));
      return true;
    } catch {
      continue;
    }
  }
  return false;
}

/**
 * Magic bytes first; a short allow-list of text formats by extension second;
 * octet-stream otherwise. The client's Content-Type is never consulted.
 */
export async function sniffMime(head: Buffer, filename: string): Promise<string> {
  const detected = await fileTypeFromBuffer(head);
  if (detected) return detected.mime;

  if (head.length === 0 || !looksLikeText(head)) return FALLBACK;

  return TEXT_EXTENSIONS[path.extname(filename).toLowerCase()] ?? FALLBACK;
}

/**
 * Reads the first `n` bytes without losing them: the consumed bytes are
 * unshifted back onto the stream, or replayed from a fresh one when the
 * source was shorter than `n` and has already ended.
 */
export function peekHead(
  stream: Readable,
  n: number,
): Promise<{ head: Buffer; body: Readable }> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let total = 0;
    let settled = false;

    const cleanup = () => {
      stream.off('readable', onReadable);
      stream.off('end', onEnd);
      stream.off('error', onError);
    };

    const finish = (ended: boolean) => {
      if (settled) return;
      settled = true;
      cleanup();

      const head = Buffer.concat(chunks);
      if (ended) {
        resolve({ head, body: Readable.from(head) });
        return;
      }
      if (head.length > 0) stream.unshift(head);
      resolve({ head, body: stream });
    };

    const onReadable = () => {
      let chunk: Buffer | null;
      while ((chunk = stream.read() as Buffer | null) !== null) {
        chunks.push(chunk);
        total += chunk.length;
        if (total >= n) {
          finish(false);
          return;
        }
      }
    };

    const onEnd = () => finish(true);

    const onError = (err: Error) => {
      if (settled) return;
      settled = true;
      cleanup();
      reject(err);
    };

    stream.on('readable', onReadable);
    stream.on('end', onEnd);
    stream.on('error', onError);
  });
}

/** RFC 5987 encoding so non-ASCII names survive the header. */
export function attachmentDisposition(filename: string): string {
  const ascii = filename.replace(/[^\x20-\x7e]/g, '_').replace(/["\\]/g, '_');
  return `attachment; filename="${ascii}"; filename*=UTF-8''${encodeURIComponent(filename)}`;
}
